name: walk_and_fit
description: App contapassi con consigli fitness e tracking calorie
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  pedometer: ^4.0.2
  permission_handler: ^11.0.1
  http: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  fl_chart: ^0.65.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android_12:
    image: assets/icon.png
    icon_background_color: "#FFFFFF"
